// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixhqkljpsqwycmxckkzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4aHFrbGpwc3F3eWNteGNra3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTYwNDIsImV4cCI6MjA2Njg5MjA0Mn0.rGxDp8go1OmIhfLy8aRbn7EXv_J9xLmzw39PkmIlnt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});